name = "PrimeNumberTheoremAnd"
defaultTargets = ["PrimeNumberTheoremAnd"]

[leanOptions]
pp.unicode.fun = true
pp.proofs.withType = false
autoImplicit = false
relaxedAutoImplicit = false
linter.mathlibStandardSet = true
linter.style.header = false
linter.style.openClassical = false
linter.style.longLine = false
linter.style.emptyLine = false
linter.flexible = true

[[require]]
name = "LeanArchitect"
git = "https://github.com/hanwenzhu/LeanArchitect.git"
rev = "main"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "leancert"
git = "https://github.com/kim-em/leancert.git"
rev = "6a30b16fbad5ea0d994b461340402e1d976a49d5"

[[require]]
name = "PrimeCert"
git = "https://github.com/b-mehta/PrimeCert"
rev = "master"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "db127794c79fdeb86f6b0cf6ff2c804026fbaff1"

[[lean_lib]]
name = "PrimeNumberTheoremAnd"
