/- LogTables.lean — Pre-computed logarithm and exponential bounds.

The natural-number entries were auto-generated by `scripts/gen_log_tables.py` using
the LeanCert Python SDK. Rational-argument entries were added by hand.
Each bound is proved by LeanCert's `interval_decide` tactic (verified Taylor series).

Reviving a centuries-old practice: Napier (1614), Briggs (1624), now Lean (2026).
-/
import LeanCert.Tactic.IntervalAuto

namespace LogTables

open Real

lemma log_2_gt : 0.693147 < log 2 := by interval_decide
lemma log_2_lt : log 2 < 0.693148 := by interval_decide

lemma log_3_gt : 1.098612 < log 3 := by interval_decide
lemma log_3_lt : log 3 < 1.098613 := by interval_decide

lemma log_5_gt : 1.609437 < log 5 := by interval_decide
lemma log_5_lt : log 5 < 1.609438 := by interval_decide

lemma log_7_gt : 1.945910 < log 7 := by interval_decide
lemma log_7_lt : log 7 < 1.945911 := by interval_decide

lemma log_10_gt : 2.302585 < log 10 := by interval_decide
lemma log_10_lt : log 10 < 2.302586 := by interval_decide

lemma log_11_gt : 2.397895 < log 11 := by interval_decide
lemma log_11_lt : log 11 < 2.397896 := by interval_decide

lemma log_13_gt : 2.564949 < log 13 := by interval_decide
lemma log_13_lt : log 13 < 2.564950 := by interval_decide

lemma log_17_gt : 2.833213 < log 17 := by interval_decide
lemma log_17_lt : log 17 < 2.833214 := by interval_decide

lemma log_19_gt : 2.944438 < log 19 := by interval_decide
lemma log_19_lt : log 19 < 2.944439 := by interval_decide

lemma log_23_gt : 3.135494 < log 23 := by interval_decide
lemma log_23_lt : log 23 < 3.135495 := by interval_decide

lemma log_29_gt : 3.367295 < log 29 := by interval_decide
lemma log_29_lt : log 29 < 3.367296 := by interval_decide

lemma log_30_gt : 3.401197 < log 30 := by interval_decide
lemma log_30_lt : log 30 < 3.401198 := by interval_decide

lemma log_32_gt : 3.465735 < log 32 := by interval_decide
lemma log_32_lt : log 32 < 3.465736 := by interval_decide

/-! ## High-precision bounds for `log 2`

These mirror `Real.log_two_gt_d9` / `Real.log_two_lt_d9` in Mathlib, restated under the
`LogTables` namespace so callers don't have to remember which library they live in. The
`d3` version is a coarser convenience bound used by several `Table 10` row arguments. -/

lemma log_2_gt_d9 : (0.6931471803 : ℝ) < log 2 := Real.log_two_gt_d9
lemma log_2_lt_d9 : log 2 < 0.6931471808 := Real.log_two_lt_d9
lemma log_2_gt_d3 : (0.6931 : ℝ) < log 2 := by linarith [log_2_gt_d9]

/-! ## Bounds on `exp(-x)` for selected `x`

Useful when an analytic-number-theory argument needs a closed-form numerical upper
bound on a tail term without paying the cost of an in-place `interval_decide`. -/

lemma exp_neg_one_lt : exp (-1 : ℝ) < 0.3678794412 := Real.exp_neg_one_lt_d9
lemma exp_neg_one_gt : (0.367879441 : ℝ) < exp (-1 : ℝ) := by interval_decide
lemma exp_neg_half_lt : exp (-(1/2 : ℝ)) < 0.6065307 := by interval_decide
lemma exp_neg_two_thirds_lt : exp (-(2/3 : ℝ)) < 0.513418 := by interval_decide

/-! ## Tail-decay master lemmas

For computations that need to bound many `exp(-x)` terms at different `x`, prove the
bound at a single threshold via `interval_decide` and use monotonicity to discharge
all other instances for free. Saves dozens of `interval_decide` invocations per file in
contexts like Table 10's regime-3 row certificates. -/

/-- For all `x ≥ 50`, `exp(-x) < 1e-20`. (Bound at the boundary is `exp(-50) ≈ 1.9e-22`.) -/
lemma exp_neg_lt_1e_neg_20 {x : ℝ} (hx : 50 ≤ x) : Real.exp (-x) < 1e-20 :=
  have h_boundary : Real.exp (-(50 : ℝ)) < 1e-20 := by interval_decide
  lt_of_le_of_lt (Real.exp_le_exp.mpr (by linarith)) h_boundary

/-- For all `x ≥ 231`, `exp(-x) < 1e-100`. (Bound at the boundary is `exp(-231) ≈ 9.8e-101`.) -/
lemma exp_neg_lt_1e_neg_100 {x : ℝ} (hx : 231 ≤ x) : Real.exp (-x) < 1e-100 :=
  have h_boundary : Real.exp (-(231 : ℝ)) < 1e-100 := by interval_decide
  lt_of_le_of_lt (Real.exp_le_exp.mpr (by linarith)) h_boundary

/-! ## Bounds for non-integer arguments -/

lemma log_2_353_gt : (0.855 : ℝ) < log 2.353 := by interval_decide
lemma log_3_2_gt : (1.163 : ℝ) < log 3.2 := by interval_decide
lemma exp_1_112_lt : exp (1.112 : ℝ) < 3.041 := by interval_decide
lemma log_6_58_gt : (1.884034 : ℝ) < log 6.58 := by interval_decide
lemma log_log_6_58_gt : (0.633415 : ℝ) < log (log 6.58) := by interval_decide

end LogTables
