#!/usr/bin/env python3
"""Generate LogTables.lean — pre-computed log bounds for small natural numbers.

Uses LeanCert's Python SDK to compute rigorous interval bounds on log(n),
then emits Lean lemmas proved by `interval_decide`.

Usage:
    python scripts/gen_log_tables.py > PrimeNumberTheoremAnd/LogTables.lean
"""

import leancert as lc
import math

# Which numbers to tabulate and at what precision (decimal digits)
ENTRIES = [2, 3, 5, 7, 10, 11, 13, 17, 19, 23, 29, 30]
PRECISION = 6  # decimal digits


def compute_bounds(n: int, digits: int):
    """Compute tight bounds on log(n) using LeanCert's verified interval arithmetic.

    Returns (lo, hi) where lo < log(n) < hi, rounded conservatively
    from the SDK's rigorous rational enclosure.
    """
    x = lc.var('x')
    cfg = lc.Config(taylor_depth=20)
    result = lc.find_bounds(lc.log(x), {'x': (n, n)}, config=cfg)

    # min_lo is a guaranteed lower bound on log(n)
    # max_hi is a guaranteed upper bound on log(n)
    # Truncate lo DOWN and hi UP to `digits` decimal places
    scale = 10 ** digits
    lo = math.floor(result.min_lo * scale) / scale
    hi = math.ceil(result.max_hi * scale) / scale
    return lo, hi


def format_decimal(val: float, digits: int) -> str:
    """Format a float as a fixed-point decimal string."""
    return f"{val:.{digits}f}"


def main():
    header = """/- LogTables.lean — Pre-computed logarithm bounds for small natural numbers.

Auto-generated by `scripts/gen_log_tables.py` using the LeanCert Python SDK.
Each bound is proved by LeanCert's `interval_decide` tactic (verified Taylor series).

Reviving a centuries-old practice: Napier (1614), Briggs (1624), now Lean (2026).
-/
import LeanCert.Tactic.IntervalAuto

namespace LogTables

open Real
"""
    print(header)

    for n in ENTRIES:
        lo, hi = compute_bounds(n, PRECISION)
        lo_str = format_decimal(lo, PRECISION)
        hi_str = format_decimal(hi, PRECISION)

        print(f"lemma log_{n}_gt : {lo_str} < log {n} := by interval_decide")
        print(f"lemma log_{n}_lt : log {n} < {hi_str} := by interval_decide")
        print()

    print("end LogTables")


if __name__ == "__main__":
    main()
